name: Pull Request

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_name: lyft/flytepropeller/operator
          image_tag: ${{ github.sha }}
          push_git_tag: true
          registry: docker.pkg.github.com
      - name: Push Docker Image to DockerHub
        uses: whoan/docker-build-with-cache-action@v5
        continue-on-error: true
        with:
          username: flytegithub2
          password: "${{ secrets.flytegithub_dockerhub }}"
          image_name: lyft/flytepropeller
          image_tag: ${{ github.sha }}
          push_git_tag: true
