name: CI

on:
  release:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push docker image
      run: DOCKER_REGISTRY_PASSWORD=${{ secrets.GITHUB_TOKEN }} make github_push
